### ISSUE TITLE
Architecture Question

### ISSUE THREAD

**Issue by aaronfranco** [prdn/pigato#21]
Hello,

This is a very promising framework, thank you for creating it! I have done a lot of work with RabbitMQ but not much at all with ZMQ. I'm interested to know what architecture this framework best represents. The architectures I'm referring to can be found in this article:

http://zeromq.org/whitepapers:brokerless 

I'm mostly concerned with how this framework will handle high concurrency at scale. Particularly, I wonder if the drawbacks outlined in the article are addressed with this framework? 

Best,
Aaron

**Comment by prdn** [comment]
Hi Aaron,

thank you for your interest.
Pigato has the Broker component, so at first glance it may seem centralised, but the goal is to build a distributed Broker infrastructure.
Broker component is fundamental to add control over the global environment and, in my opinion, is more suitable for enterprise deployment. On the Broker you can handle Client and Worker authentication, access control, balancing, ... there are lot of reasons to have a Broker (as explained in the page you linked).
Broker is also helpful when Workers are not in the same subnetwork or on different geographical networks or when Clients cannot connect directly to Workers.

I would like to describe here some goals of Pigato, that are already implemented or part Pigato's future:
- Infinite idempotent Brokers to avoid bottlenecks
- Client and Workers can connect to multiple Brokers
- Manual or automatic (future) Client request resubmitting on failure
- (future) Broadcast requests through single Broker or multiple Brokers
- (future) Pigato should offer more than Router / Dealer approach, but will let implement easily other patterns.
- (future) Directory Service: for some services we may want to let Clients connect directly to Workers, so the Broker can notify Clients the Workers addresses. Clients may connect directly (if allowed) to Workers via REQ/REP pattern. This also goes in the direction of the Broker(less) model, it is P2P oriented and helps also in performances reducing connections to 1hop. 

My first goal in Pigato, however, is to keep everything simple to have always control over the distribution model.  Non core features will be implemented as "special" workers that interact with the Broker to extend its functionalities.

Let's say we want to offer map-reduce functionality so that all the Workers offering a service are queried and then the result is aggregated... this may be the proposed structure
- add the functionality to a Broker to send the list of workerIds offering a given service (with a special permission eventually)
- let Client to specify in the Request options the workerId that should handle the request
- a Client requests a map-reduce for the service db.query
- the map-reduce special Worker will request to the Broker the list of workerIds that are offering the db.query service. Then the map-reduce special Worker creates an internal Client that sends N requests, one for each Worker, specifying for each request a workerId. When it receives all the replies from the Workers it reduce everything to a single reply and replies back to the original Client.

We could add that functionality into the Broker, but I don't want complex Brokers. Brokers should be easily deployable and have basic features. This is really important to build a scalable and truly distributed system.

Finally Pigato is in heavy development, so any help that follows or can improve the Pigato idea.

**Comment by prdn** [comment]
@aaronfranco please take a look to this commit f7127f2 , this file https://github.com/prdn/pigato/blob/master/services/Directory.js and this test https://github.com/prdn/pigato/blob/master/test/directory.js
The distributed directory is near.
